/* ============================================================================
 * FM-182 — the ground station must be able to compute the companion's
 * `record_hash` byte-for-byte, or every mission record it stamps is refused
 * (or, worse, the monitor runs against a record nobody verified).
 *
 * The expectations in `fixtures/record_hash_parity.json` were GENERATED by the
 * companion's own `security.py` helper, so this suite fails the moment the two
 * implementations disagree — including on key ordering, excluded fields and
 * non-ASCII encoding, each of which has its own case.
 * ========================================================================== */
import * as fs from 'fs';
import * as path from 'path';
import { describe, expect, it } from 'vitest';
import {
  GENESIS_HASH, canonicalRecordJson, chainHash, recordHash, sha256Hex, stampRecordHash,
} from '../src/security';

interface ParityCase {
  name: string;
  record: Record<string, unknown>;
  recordHash: string;
  chainHashFromGenesis: string;
  chainHashFromPrev: string;
}
const parity = JSON.parse(fs.readFileSync(
  path.resolve(__dirname, 'fixtures/record_hash_parity.json'), 'utf8')) as {
    genesisHash: string; cases: ParityCase[];
  };

/** RFC 6234 / NIST test vectors, so a broken SHA-256 fails on its own terms. */
const SHA_VECTORS: Array<[string, string]> = [
  ['', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'],
  ['abc', 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'],
  ['abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq',
    '248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1'],
];

describe('sha256Hex', () => {
  for (const [input, digest] of SHA_VECTORS) {
    it(`matches the published vector for ${JSON.stringify(input.slice(0, 12))}`, () => {
      expect(sha256Hex(new TextEncoder().encode(input))).toBe(digest);
    });
  }

  it('hashes across the 55/56/64-byte padding boundaries', () => {
    // One block, two blocks, and exactly-one-block inputs take different
    // padding paths; a length bug shows up here and nowhere else.
    for (const length of [55, 56, 63, 64, 65, 119, 120]) {
      const text = 'a'.repeat(length);
      expect(sha256Hex(new TextEncoder().encode(text))).toMatch(/^[0-9a-f]{64}$/);
    }
    expect(sha256Hex(new TextEncoder().encode('a'.repeat(56))))
      .toBe('b35439a4ac6f0948b6d6f9e3c6af0f5f590ce20f1bde7090ef7970686ec6738a');
  });
});

describe('record hash parity with companion/security.py', () => {
  it('agrees on the genesis hash', () => {
    expect(GENESIS_HASH).toBe(parity.genesisHash);
  });

  for (const testCase of parity.cases) {
    it(`reproduces the Python record_hash: ${testCase.name}`, () => {
      expect(recordHash(testCase.record)).toBe(testCase.recordHash);
    });
    it(`reproduces the Python chain_hash: ${testCase.name}`, () => {
      expect(chainHash('', testCase.record)).toBe(testCase.chainHashFromGenesis);
      expect(chainHash('a'.repeat(64), testCase.record)).toBe(testCase.chainHashFromPrev);
    });
  }
});

describe('canonical form', () => {
  it('sorts keys at every depth and emits no whitespace', () => {
    expect(canonicalRecordJson({ b: 1, a: { d: 2, c: 3 } })).toBe('{"a":{"c":3,"d":2},"b":1}');
  });

  it('excludes the chain and identity fields', () => {
    const body = { missionId: 'm', sig: 's', hash: 'h', prev: 'p', recordHash: 'r' };
    expect(canonicalRecordJson(body)).toBe('{"missionId":"m"}');
  });

  it('drops undefined the way Python has no such value', () => {
    expect(recordHash({ a: 1, b: undefined })).toBe(recordHash({ a: 1 }));
  });

  it('refuses a non-finite number instead of silently emitting null', () => {
    expect(() => recordHash({ alt: Number.NaN })).toThrow(/no portable representation/);
    expect(() => recordHash({ alt: Number.POSITIVE_INFINITY })).toThrow(/no portable representation/);
  });
});

describe('stampRecordHash', () => {
  it('stamps a hash the record verifies against', () => {
    const record = { missionId: 'plan-1', vehicleId: 'eis-1', startedAt: 1757116800000 };
    const stamped = stampRecordHash(record);
    // The companion recomputes over the record INCLUDING the stamp, which is
    // excluded — so stamping twice is idempotent and self-verifying.
    expect(recordHash(stamped)).toBe(stamped.recordHash);
    expect(stampRecordHash(stamped).recordHash).toBe(stamped.recordHash);
  });
});
