<#
.SYNOPSIS
  Serve ONE looping synthetic clip over RTSP for the CCTV rail's PIXEL fallback.

.DESCRIPTION
  A stand-in for a camera, not a camera: the clip is generated by ffmpeg's lavfi
  sources (a coloured background plus a moving rectangle where a person would
  be). Nothing here was filmed and no site was observed.

  The pixel path is off unless EIS_CCTV_MODE=pixel, so nothing on the demo or
  test path depends on this script, on ffmpeg, or on anything listening.

  ffmpeg serves the stream itself (-rtsp_flags listen), so no separate RTSP
  server is needed. It accepts ONE client, which is all the one-stream fallback
  is scoped for.

.EXAMPLE
  ./cctv-loop.ps1
  # rtsp://127.0.0.1:8554/cam-east-south

.EXAMPLE
  ./cctv-loop.ps1 -Camera cam-east-north -Port 8555
#>
[CmdletBinding()]
param(
  [string] $Camera = 'cam-east-south',
  [int]    $Port = 8554,
  [string] $ClientHost = $(if ($env:EIS_CCTV_RTSP_HOST) { $env:EIS_CCTV_RTSP_HOST } else { '127.0.0.1' }),
  [int]    $DurationSeconds = $(if ($env:EIS_CCTV_CLIP_SECONDS) { [int]$env:EIS_CCTV_CLIP_SECONDS } else { 20 })
)

$ErrorActionPreference = 'Stop'

$ffmpeg = if ($env:FFMPEG) { $env:FFMPEG } else { 'ffmpeg' }
if (-not (Get-Command $ffmpeg -ErrorAction SilentlyContinue)) {
  Write-Error "cctv-loop: ffmpeg ($ffmpeg) is not on PATH. The pixel fallback cannot run; CCTV event mode is unaffected."
  exit 127
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$clip = Join-Path $scriptDir '..\fixtures\cctv-loop.mp4'

if (-not (Test-Path $clip)) {
  Write-Output "cctv-loop: generating a ${DurationSeconds}s synthetic clip at $clip"
  $overlay = "[0:v][1:v]overlay=x='140+1000*t/$DurationSeconds':y=520"
  & $ffmpeg -y -hide_banner -loglevel error `
    -f lavfi -i "color=c=0x2b3a2f:s=1280x720:r=25:d=$DurationSeconds" `
    -f lavfi -i "color=c=0xd8c9a3:s=40x92:r=25:d=$DurationSeconds" `
    -filter_complex $overlay `
    -t $DurationSeconds -c:v libx264 -preset veryfast -pix_fmt yuv420p -g 25 `
    $clip
  if ($LASTEXITCODE -ne 0) { Write-Error "cctv-loop: clip generation failed ($LASTEXITCODE)"; exit $LASTEXITCODE }
}

$url = "rtsp://${ClientHost}:${Port}/$Camera"
Write-Output "cctv-loop: serving $clip on $url (looping; Ctrl-C to stop)"
Write-Output 'cctv-loop: point the rail at it with EIS_CCTV_MODE=pixel'

& $ffmpeg -hide_banner -loglevel warning `
  -re -stream_loop -1 -i $clip `
  -c copy -f rtsp -rtsp_transport tcp -rtsp_flags listen $url
exit $LASTEXITCODE
