#!/usr/bin/env bash
# =============================================================================
# cctv-loop.sh — serve ONE looping synthetic clip over RTSP, for the CCTV
# rail's PIXEL fallback (EIS_CCTV_MODE=pixel).
#
# This is a stand-in for a camera, not a camera: the clip is generated by
# ffmpeg's lavfi sources (a coloured background plus a moving rectangle where a
# person would be). Nothing here was filmed, and no site was observed.
#
# The pixel path is off by default, so nothing on the demo or test path depends
# on this script, on ffmpeg, or on anything listening.
#
#   ./cctv-loop.sh                       # rtsp://127.0.0.1:8554/cam-east-south
#   ./cctv-loop.sh cam-east-north 8554   # a different camera / port
#
# ffmpeg serves the stream itself (`-rtsp_flags listen`), so no separate RTSP
# server is needed. It accepts ONE client — which is all the one-stream fallback
# is scoped for.
# =============================================================================
set -euo pipefail

CAMERA="${1:-cam-east-south}"
PORT="${2:-8554}"
HOST="${EIS_CCTV_RTSP_HOST:-127.0.0.1}"
FFMPEG="${FFMPEG:-ffmpeg}"
DURATION="${EIS_CCTV_CLIP_SECONDS:-20}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLIP="${SCRIPT_DIR}/../fixtures/cctv-loop.mp4"

if ! command -v "${FFMPEG}" >/dev/null 2>&1; then
  echo "cctv-loop: ffmpeg (${FFMPEG}) is not on PATH." >&2
  echo "cctv-loop: the pixel fallback cannot run; CCTV event mode is unaffected." >&2
  exit 127
fi

if [ ! -f "${CLIP}" ]; then
  echo "cctv-loop: generating a ${DURATION}s synthetic clip at ${CLIP}"
  "${FFMPEG}" -y -hide_banner -loglevel error \
    -f lavfi -i "color=c=0x2b3a2f:s=1280x720:r=25:d=${DURATION}" \
    -f lavfi -i "color=c=0xd8c9a3:s=40x92:r=25:d=${DURATION}" \
    -filter_complex "[0:v][1:v]overlay=x='140+1000*t/${DURATION}':y=520" \
    -t "${DURATION}" -c:v libx264 -preset veryfast -pix_fmt yuv420p -g 25 \
    "${CLIP}"
fi

URL="rtsp://${HOST}:${PORT}/${CAMERA}"
echo "cctv-loop: serving ${CLIP} on ${URL} (looping; Ctrl-C to stop)"
echo "cctv-loop: point the rail at it with EIS_CCTV_MODE=pixel"

exec "${FFMPEG}" -hide_banner -loglevel warning \
  -re -stream_loop -1 -i "${CLIP}" \
  -c copy -f rtsp -rtsp_transport tcp -rtsp_flags listen "${URL}"
